---
- name: "Deploy marzban main node"
  hosts: "marzban"
  gather_facts: false
  become: true
  tasks:
    - name: "Import common role"
      import_role:
        name: common
      tags: common
    - name: "Import docker role"
      import_role:
        name: docker
      tags: docker
    - name: "Import marzban role"
      import_role:
        name: marzban
      tags: marzban
