---

# Порты которые нужно открыть на minion(node) ноде (ssh уже включен в роль)
common_open_ports: "{{ common_open_ports_additional + marzban_api_ports }}"

common_open_ports_additional:
  - "80"
  - "443"
