---

- name: "Common | Set timezone to {{ timezone }}"
  community.general.timezone:
    name: "{{ timezone }}"


- name: "Common | Set hostname to hosts"
  ansible.builtin.hostname:
   name: "{{ inventory_hostname }}.{{ domain }}"
