---

- name: "Common | {{ role | upper() }} | UFW | Reset all rules"
  community.general.ufw:
    state: reset

- name: "Common | {{ role | upper() }} | UFW | Allow ports per node"
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
  with_items:
    - "{{ common_open_ports }}"

- name: "Common | {{ role | upper() }} | UFW | Limit ssh connections"
  community.general.ufw:
    rule: limit
    port: "{{ item }}"
  with_items:
    - "{{ change_sshd_port_configured_port }}"

- name: "Common | {{ role | upper() }} | UFW | Deny outbound traffic to private networks"
  community.general.ufw:
    rule: deny
    direction: out
    to_ip: "{{ item }}"
  with_items:
    - "{{ common_closed_networks }}"

- name: "Common | {{ role | upper() }} | UFW | Enable firewall service"
  community.general.ufw:
    state: enabled
